// <auto-generated />
namespace BasicDb.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addCharItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCharItem));
        
        string IMigrationMetadata.Id
        {
            get { return "202003042049287_addCharItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
